basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is an backend Api just for Belva Philips website
  termsOfService: http://swagger.io/terms/
  title: Belva Philips Backend API
  version: "1.0"
paths: {}
swagger: "2.0"
